# Generated by Django 3.2 on 2021-05-25 15:50

import core.models
import core.storages
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('created', models.DateTimeField(editable=False, verbose_name='생성 된 시간')),
                ('updated', models.DateTimeField(verbose_name='최근 업데이트 시간')),
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('link', models.URLField(blank=True, max_length=300, verbose_name='링크')),
                ('is_verified', models.BooleanField(default=False, help_text='에디터가 검증한 여부, 에디터가 올린 테마는 기본값 True', verbose_name='검증 여부')),
                ('is_confirm', models.BooleanField(default=False, help_text='신고가 들어온 테마를 에디터가 확인한 여부', verbose_name='확인 여부')),
                ('is_pending', models.BooleanField(default=False, help_text='신고등의 이유로 게시가 보류가 됬는지 여부', verbose_name='보류 여부')),
                ('post_start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='게시 시작일')),
                ('post_end_datetime', models.DateTimeField(default=datetime.datetime(2071, 5, 22, 9, 0), verbose_name='게시 종료일')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='가격')),
            ],
            options={
                'verbose_name': '테마',
                'verbose_name_plural': '테마',
            },
        ),
        migrations.CreateModel(
            name='ThemeTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(editable=False, verbose_name='생성 된 시간')),
                ('updated', models.DateTimeField(verbose_name='최근 업데이트 시간')),
                ('tag', models.CharField(max_length=20, verbose_name='태그')),
            ],
            options={
                'verbose_name': '테마 태그',
                'verbose_name_plural': '테마 태그',
            },
        ),
        migrations.CreateModel(
            name='ThemeThumbnail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(editable=False, verbose_name='생성 된 시간')),
                ('updated', models.DateTimeField(verbose_name='최근 업데이트 시간')),
                ('image_size_type', models.CharField(choices=[('default', '기본'), ('origin', '원본'), ('mini', '작은'), ('micro', '아주 작은')], default='default', max_length=10, verbose_name='이미지 크기 종류')),
                ('image', models.ImageField(storage=core.storages.OverwriteStorage(), upload_to=core.models.fleet_thumbnail_path, verbose_name='썸네일')),
                ('image_type', models.CharField(default='image', max_length=20, verbose_name='이미지 형식')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='가로')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='세로')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='themes.theme', verbose_name='테마')),
            ],
            options={
                'verbose_name': '테마 썸네일',
                'verbose_name_plural': '테마 썸네일',
            },
        ),
        migrations.CreateModel(
            name='ThemeContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(editable=False, verbose_name='생성 된 시간')),
                ('updated', models.DateTimeField(verbose_name='최근 업데이트 시간')),
                ('screen_size', models.CharField(choices=[('normal', '일반'), ('large', '큰')], default='normal', max_length=10, verbose_name='화면크기')),
                ('content', models.FileField(storage=core.storages.OverwriteStorage(), upload_to=core.models.fleet_content_path, verbose_name='컨텐츠')),
                ('content_type', models.CharField(default='', max_length=20, verbose_name='컨텐츠 형식')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='가로')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='세로')),
                ('preload', models.ImageField(storage=core.storages.OverwriteStorage(), upload_to=core.models.fleet_preload_path, verbose_name='프리로드')),
                ('preload_type', models.CharField(default='', max_length=20, verbose_name='프리로드 형식')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='themes.theme', verbose_name='테마')),
            ],
            options={
                'verbose_name': '테마 컨텐츠',
                'verbose_name_plural': '테마 컨텐츠',
            },
        ),
    ]
