# Generated by Django 3.2 on 2021-05-25 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL, verbose_name='소유자'),
        ),
        migrations.AddField(
            model_name='theme',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='themes', to='themes.ThemeTag', verbose_name='태그'),
        ),
    ]
