# Generated by Django 3.2.4 on 2021-07-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='is_confirm',
        ),
        migrations.AddField(
            model_name='theme',
            name='dominant_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='대표색'),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_public',
            field=models.BooleanField(default=True, help_text='신고등의 이유로 게시가 보류가 됬는지 여부', verbose_name='공개 여부'),
        ),
    ]
