# Generated by Django 3.2.4 on 2021-06-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frames', '0002_themeframe_owner'),
        ('themes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterThemeLinkLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(editable=False, verbose_name='생성 된 시간')),
                ('updated', models.DateTimeField(verbose_name='최근 업데이트 시간')),
                ('device_id', models.CharField(editable=False, max_length=50, verbose_name='디바이스 ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter_link_logs', to='themes.theme', verbose_name='테마')),
            ],
            options={
                'verbose_name': '테마 링크 사용 기록',
                'verbose_name_plural': '테마 링크 사용 기록',
            },
        ),
        migrations.CreateModel(
            name='EncodingLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(editable=False, verbose_name='생성 된 시간')),
                ('updated', models.DateTimeField(verbose_name='최근 업데이트 시간')),
                ('device_id', models.CharField(editable=False, max_length=50, verbose_name='디바이스 ID')),
                ('resource_type', models.CharField(choices=[('gif', 'GIF'), ('video', '비디오')], default='video', max_length=10, verbose_name='리소스 종류')),
                ('src_duration', models.IntegerField(default=0, verbose_name='원본영상길이')),
                ('dst_duration', models.IntegerField(default=0, verbose_name='편집영상길이')),
                ('frame_type', models.CharField(choices=[('base', '기본'), ('template', '템플릿')], default='base', max_length=15, verbose_name='프레임 종류')),
                ('is_cut', models.BooleanField(default=False, verbose_name='자르기 여부')),
                ('is_boomerang', models.BooleanField(default=False, verbose_name='부메랑 여부')),
                ('bg_color', models.CharField(default='#000000', max_length=7, verbose_name='배경색')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoding_logs', to='frames.themeframe', verbose_name='템플릿')),
            ],
            options={
                'verbose_name': '인코딩 기록',
                'verbose_name_plural': '인코딩 기록',
            },
        ),
        migrations.CreateModel(
            name='ApplingThemeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(editable=False, verbose_name='생성 된 시간')),
                ('updated', models.DateTimeField(verbose_name='최근 업데이트 시간')),
                ('device_id', models.CharField(editable=False, max_length=50, verbose_name='디바이스 ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appling_logs', to='themes.theme', verbose_name='테마')),
            ],
            options={
                'verbose_name': '적용중인 테마 기록',
                'verbose_name_plural': '적용중인 테마 기록',
            },
        ),
        migrations.CreateModel(
            name='AppliedThemeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(editable=False, verbose_name='생성 된 시간')),
                ('updated', models.DateTimeField(verbose_name='최근 업데이트 시간')),
                ('device_id', models.CharField(editable=False, max_length=50, verbose_name='디바이스 ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_logs', to='themes.theme', verbose_name='테마')),
            ],
            options={
                'verbose_name': '테마 적용 기록',
                'verbose_name_plural': '테마 적용 기록',
            },
        ),
    ]
