# Generated by Django 3.2 on 2021-05-25 15:50

import core.models
import core.storages
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeCurationFolder',
            fields=[
                ('created', models.DateTimeField(editable=False, verbose_name='생성 된 시간')),
                ('updated', models.DateTimeField(verbose_name='최근 업데이트 시간')),
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=12, verbose_name='제목')),
                ('sub_title', models.CharField(blank=True, default='', max_length=16, verbose_name='소제목')),
                ('description', models.CharField(blank=True, default='', max_length=16, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='순서')),
            ],
            options={
                'verbose_name': '테마 큐레이션 폴더',
                'verbose_name_plural': '테마 큐레이션 폴더',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='ThemeCurationGroup',
            fields=[
                ('created', models.DateTimeField(editable=False, verbose_name='생성 된 시간')),
                ('updated', models.DateTimeField(verbose_name='최근 업데이트 시간')),
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=12, verbose_name='제목')),
                ('view_type', models.CharField(choices=[('L_HorizontalScroll', '횡 스크롤 뷰 L'), ('M_HorizontalScroll', '횡 스크롤 뷰 M'), ('S_HorizontalScroll', '횡 스크롤 뷰 S'), ('List', '리스트 뷰'), ('SquareAlbum', '앨범뷰 (Square)')], default='L_HorizontalScroll', max_length=30, verbose_name='뷰 유형')),
                ('post_start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='게시 시작일')),
                ('post_end_datetime', models.DateTimeField(default=datetime.datetime(2071, 5, 22, 9, 0), verbose_name='게시 종료일')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='순서')),
            ],
            options={
                'verbose_name': '테마 큐레이션 그룹',
                'verbose_name_plural': '테마 큐레이션 그룹',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='ThemeCurationFolderCover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(editable=False, verbose_name='생성 된 시간')),
                ('updated', models.DateTimeField(verbose_name='최근 업데이트 시간')),
                ('image_size_type', models.CharField(choices=[('default', '기본'), ('origin', '원본'), ('mini', '작은'), ('micro', '아주 작은')], default='default', max_length=10, verbose_name='이미지 크기 종류')),
                ('image', models.ImageField(storage=core.storages.OverwriteStorage(), upload_to=core.models.fleet_thumbnail_path, verbose_name='썸네일')),
                ('image_type', models.CharField(default='image', max_length=20, verbose_name='이미지 형식')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='가로')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='세로')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='curations.themecurationfolder', verbose_name='폴더')),
            ],
            options={
                'verbose_name': '폴더 커버',
                'verbose_name_plural': '폴더 커버',
            },
        ),
        migrations.AddField(
            model_name='themecurationfolder',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='curations.themecurationgroup', verbose_name='그룹'),
        ),
    ]
