# Generated by Django 3.2 on 2021-05-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(editable=False, verbose_name='생성 된 시간')),
                ('updated', models.DateTimeField(verbose_name='최근 업데이트 시간')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='순서')),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='curations.themecurationfolder', verbose_name='폴더')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='curations.themecurationgroup', verbose_name='그룹')),
            ],
            options={
                'verbose_name': '테마 목록',
                'verbose_name_plural': '테마 목록',
            },
        ),
    ]
