# Generated by Django 3.2 on 2021-05-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themelist',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='themes.theme', verbose_name='테마'),
        ),
    ]
