# Generated by Django 3.2 on 2021-05-31 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload_stop_period',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='업로드 정지 기한'),
        ),
    ]
