# Generated by Django 3.2.4 on 2021-07-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_upload_stop_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_usable_editor',
        ),
    ]
