# Generated by Django 3.2.4 on 2021-07-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_usable_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dominant_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='대표색'),
        ),
    ]
